name: Notifications
on:
  issues:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Post notification (PR)
        if: github.event_name == 'pull_request'
        run: |
          curl -i -X POST -H "Content-Type: application/json" \
            -d "{ \
              \"channel_id\": \"${{ secrets.CHANNEL_ID }}\", \
              \"text\": \"Pull Request ${{ github.event.action }}, ${GITHUB_REF}\" \
              }" \
            ${{ secrets.WEBHOOK_URI }}
      - name: Post notification (Issue)
        if: github.event_name == 'issues' && github.event.action == 'opened'
        run: |
          curl -i -X POST -H "Content-Type: application/json" \
            -d "{ \
              \"channel_id\": \"${{ secrets.CHANNEL_ID }}\", \
              \"text\": \"New Issue: ${{ github.event.action }}, ${GITHUB_REF}\" \
              }" \
            ${{ secrets.WEBHOOK_URI }}
